2020-05-02 12:18:46.166741: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2020-05-02 12:18:46.166851: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2020-05-02 12:18:46.166861: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-05-02 12:18:49.270496: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2020-05-02 12:18:49.270530: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-05-02 12:18:49.270553: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (gl3084.arc-ts.umich.edu): /proc/driver/nvidia/version does not exist
2020-05-02 12:18:49.270903: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-05-02 12:18:49.276602: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2020-05-02 12:18:49.276783: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x558e6c5bf4e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-02 12:18:49.276801: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[[ 9.99928687e-01  5.15363856e-05  3.47176646e-06 ...  2.20238180e-03
   1.03024868e-03  1.86161822e-03]
 [ 5.15363856e-05  9.99914640e-01 -3.42820389e-05 ... -2.58575815e-03
  -4.51321975e-04  4.80510264e-04]
 [ 3.47176646e-06 -3.42820389e-05  9.99978850e-01 ... -7.63695793e-04
   1.43468950e-04  1.11507031e-03]
 ...
 [ 2.20238180e-03 -2.58575815e-03 -7.63695793e-04 ...  9.11442685e-01
  -2.57592549e-02 -1.97681295e-02]
 [ 1.03024868e-03 -4.51321975e-04  1.43468950e-04 ... -2.57592549e-02
   9.83329245e-01 -3.80214060e-02]
 [ 1.86161822e-03  4.80510264e-04  1.11507031e-03 ... -1.97681295e-02
  -3.80214060e-02  8.82116015e-01]]
Done step 200

Done step 400

Done step 600

Done step 800

Done step 1000

/sw/arcts/centos7/python3.6-anaconda/5.2.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
CPU count 36

Time taken 0.01132892370223999

Total time taken 1.132892370223999
Traceback (most recent call last):
  File "adversarial_sample.py", line 89, in <module>
    np.save(perturbed_samples, filename)
  File "/sw/arcts/centos7/python3.6-anaconda/5.2.0/lib/python3.6/site-packages/numpy/lib/npyio.py", line 521, in save
    file = os_fspath(file)
TypeError: expected str, bytes or os.PathLike object, not numpy.ndarray
