2020-05-02 12:20:36.238042: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2020-05-02 12:20:36.238452: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2020-05-02 12:20:36.238464: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2020-05-02 12:20:39.144517: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /sw/arcts/centos7/python3.6-anaconda/5.2.0/lib:/opt/slurm/lib64::
2020-05-02 12:20:39.144553: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-05-02 12:20:39.144575: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (gl3084.arc-ts.umich.edu): /proc/driver/nvidia/version does not exist
2020-05-02 12:20:39.144917: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2020-05-02 12:20:39.150436: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3000000000 Hz
2020-05-02 12:20:39.150587: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x559bccb78f60 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-02 12:20:39.150598: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[[ 9.99928687e-01  5.15363856e-05  3.47176646e-06 ...  2.20238180e-03
   1.03024868e-03  1.86161822e-03]
 [ 5.15363856e-05  9.99914640e-01 -3.42820389e-05 ... -2.58575815e-03
  -4.51321975e-04  4.80510264e-04]
 [ 3.47176646e-06 -3.42820389e-05  9.99978850e-01 ... -7.63695793e-04
   1.43468950e-04  1.11507031e-03]
 ...
 [ 2.20238180e-03 -2.58575815e-03 -7.63695793e-04 ...  9.11442685e-01
  -2.57592549e-02 -1.97681295e-02]
 [ 1.03024868e-03 -4.51321975e-04  1.43468950e-04 ... -2.57592549e-02
   9.83329245e-01 -3.80214060e-02]
 [ 1.86161822e-03  4.80510264e-04  1.11507031e-03 ... -1.97681295e-02
  -3.80214060e-02  8.82116015e-01]]
Done step 200

Done step 400

Done step 600

Done step 800

Done step 1000

/sw/arcts/centos7/python3.6-anaconda/5.2.0/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
CPU count 36

Time taken 0.012388119697570801

Total time taken 1.23881196975708
Traceback (most recent call last):
  File "adversarial_sample.py", line 94, in <module>
    tf.keras.utils.plot_model(model, to_file = imagename, show_shapes=True)
  File "/home/smaity/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/vis_utils.py", line 283, in plot_model
    dpi=dpi)
  File "/home/smaity/.local/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/vis_utils.py", line 110, in model_to_dot
    raise ImportError('Failed to import pydot. You must install pydot'
ImportError: Failed to import pydot. You must install pydot and graphviz for `pydotprint` to work.
